const actionTypes = {
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  SIGN_UP_USER: 'SIGN_UP_USER',
  SET_USER: 'SET_USER',
  REMOVE_USER: 'REMOVE_USER',
  GET_FEATURED_POSTS: 'GET_FEATURED_POSTS',
  GET_POSTS: 'GET_POSTS',
  GET_PAGINATION_LENGTH: 'GET_PAGINATION_LENGTH',
  SET_ERROR: 'SET_ERROR'
};

export default actionTypes;
