const actionTypes = {
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  SIGN_UP_USER: 'SIGN_UP_USER',
  SET_TOKEN: 'SET_TOKEN',
  DELETE_TOKEN: 'DELETE_TOKEN',
  SET_USER: 'SET_USER',
  REMOVE_USER: 'REMOVE_USER',
  GET_FEATURED_POSTS: 'GET_FEATURED_POSTS',
  GET_POSTS: 'GET_POSTS',
  GET_SINGLE_POST: 'GET_SINGLE_POST',
  GET_PAGINATION_LENGTH: 'GET_PAGINATION_LENGTH',
  UPLOAD_NEW_POST: 'UPLOAD_NEW_POST',
  CLEAR_UPLOAD_NEW_POST: 'CLEAR_UPLOAD_NEW_POST',
  SET_ERROR: 'SET_ERROR'
};

export default actionTypes;
